# Generated by Django 4.0.6 on 2022-09-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_created_date_alter_job_job_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '候选人', 'verbose_name_plural': '候选人'},
        ),
    ]
