# Generated by Django 4.0.6 on 2022-09-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '招聘岗位', 'verbose_name_plural': '招聘岗位'},
        ),
    ]
