# Generated by Django 4.2.1 on 2023-07-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mef_date', models.DateTimeField(null=True, verbose_name='获取mef时间')),
                ('mef_server_name', models.CharField(max_length=20, verbose_name='服务器名称')),
                ('mef_report_file', models.FileField(max_length=254, upload_to='uploads/%Y/%m/%d/', verbose_name='文件名')),
            ],
        ),
    ]
